use crate::shell::Shell;
use crate::state::State;
use std::fs::{self, File, OpenOptions};
use std::io::Write;
use std::path::PathBuf;

fn get_oracle_file_path(shell: Shell) -> PathBuf {
    dirs::config_dir()
        .unwrap()
        .join("oracle")
        .join(match shell {
            Shell::Bash => "oracle.sh",
            Shell::Zsh => "oracle.zsh",
            _ => unreachable!("mumma!"),
        })
}

fn get_shell_profile_path(shell: Shell) -> PathBuf {
    dirs::home_dir().unwrap().join(match shell {
        Shell::Bash => ".bashrc",
        Shell::Zsh => ".zshrc",
        _ => unreachable!("it's too christpilled..."),
    })
}

pub fn ensure_oracle_file_is_sourced(shell: Shell) -> std::io::Result<()> {
    let oracle_path = get_oracle_file_path(shell);
    let profile_path = get_shell_profile_path(shell);

    let source_line = format!("source \"{}\"", oracle_path.to_str().unwrap());

    // ensure oracle_path exists and is a file
    if let Some(parent) = oracle_path.parent() {
        fs::create_dir_all(parent)?;
    }
    if !oracle_path.exists() {
        fs::write(&oracle_path, "")?;
    }

    let contents = fs::read_to_string(&profile_path).unwrap_or_default();

    if contents.lines().any(|line| line.trim() == source_line) {
        return Ok(());
    }

    let mut profile_file = OpenOptions::new()
        .create(true)
        .append(true)
        .open(&profile_path)?;

    writeln!(profile_file, "\n# added by oracle\n{source_line}")?;

    Ok(())
}

pub fn write_vars_to_oracle_sh(shell: Shell, vars: &[(String, String)]) -> std::io::Result<()> {
    let mut contents = "# Generated by Oracle, generational dharma loss if edited!\n\n".to_string();
    for (k, v) in vars {
        contents.push_str(&format!("export {k}='{v}'"));
    }

    fs::write(&get_shell_profile_path(shell), contents)?;

    Ok(())
}
